import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "@/libs/redis";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import TranslationsProvider from "@/components/TranslationsProvider";
import initTranslations from "../../i18n";
import { getLocale } from "@/utils/get-locale";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const namespaces = ["translations"];

export default async function RootLayout({ children }: RootLayoutProps) {
  const get_locale = await getLocale();
  const { resources, locale } = await initTranslations(get_locale, namespaces);

  return (
    <html lang={locale || "en"} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TranslationsProvider
            namespaces={namespaces}
            locale={locale}
            resources={resources}
          >
            {children}
            <Toaster position="top-right" />
          </TranslationsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
