import { Router } from "express";
import admin from "./admin/route.admin";
import setting from "./settings/setting";
import route_telegram from "./telegram/route.telegram";
import upload from "./upload/upload";
import route_user from "./user/index";
import route_bot from "./bot/route";
import { middleware } from "../../middleware/middleware";
const ensureAuth = middleware.ensureAuthenticated;
const router = Router();
router.use("/bot", route_bot);
router.use("/admin", ensureAuth, admin);
router.use("/setting", ensureAuth, setting);
router.use("/telegram", ensureAuth, route_telegram);
router.use("/upload", ensureAuth, upload);
router.use("/user", ensureAuth, route_user);
export default router;